export const enum DataDependenceOptions {
  FULL,
  NO_BASE_NO_EXCEPTIONS,
  NO_BASE_NO_HEAP,
  NO_BASE_NO_HEAP_NO_EXCEPTIONS,
  NO_BASE_PTRS,
  NO_EXCEPTIONS,
  NO_HEAP,
  NO_HEAP_NO_EXCEPTIONS,
  NONE,
  REFLECTION
}
